# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [1]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

In [2]:
# 1차원 배열 생성하기
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# type 확인
type(arr)

numpy.ndarray

In [4]:
# array 함수에는 data에 object 1개 하나만 들어가야 한다
np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [5]:
# 데이터 타입 확인
arr.dtype

dtype('int32')

In [6]:
# overflow 테스트
arr = np.array([2147483648,2,3,4], dtype = np.int64)
arr

array([2147483648,          2,          3,          4], dtype=int64)

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr = np.array([1,2,3,4], dtype = float)
arr

array([1., 2., 3., 4.])

In [9]:
arr.dtype

dtype('float64')

In [10]:
# shape : 배열의 생긴모습, 각차원의 배열의 size(차원의 모양)
arr.shape #(1차원 요소개수,) , tuple로 return

(4,)

In [11]:
# size : 배열 전체의 요소의 개수
arr.size #속성

4

In [12]:
# ndim : 차원의 수
arr.ndim # 속성

1

In [13]:
# ndarray에는 같은 데이터만 들어가야 함
arr = np.array([1,2,3,3.14])
arr #자동으로 업 캐스팅 (int -> float)

array([1.  , 2.  , 3.  , 3.14])

In [14]:
arr.dtype = int
arr

array([         0, 1072693248,          0, 1073741824,          0,
       1074266112, 1374389535, 1074339512])

In [18]:
# int, float => int
arr = np.array([1,2,3,3.14], dtype = int)
arr

array([1, 2, 3, 3])

In [19]:
# int, float, string -> 자동으로 string
# >(big-endian), <(little-endian)
# 32-character string
arr = np.array([1,3.14,'123456789012345678901234567890123'])
arr

array(['1', '3.14', '123456789012345678901234567890123'], dtype='<U33')

In [20]:
arr = np.array([1,3.14,'123456789012345678901234567890123'], dtype = '<U32')
arr # 32자에서 잘린다!

array(['1', '3.14', '12345678901234567890123456789012'], dtype='<U32')

In [21]:
# 기존의 배열을 이용하여 type이 다른 배열을 생성하기
new_arr = arr.astype(float) # float 타입으로 배열 바꿈
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+31])

In [22]:
arr.dtype, new_arr.dtype

(dtype('<U32'), dtype('float64'))

## 2차원 배열 생성하기

In [23]:
arr2 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]], dtype = float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [24]:
type(arr2)

numpy.ndarray

In [25]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('float64'), (3, 4), 12, 2)

In [26]:
new_arr2 = arr2.astype(int)
new_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arange() 함수로 생성하기

### 1차원 배열 생성하기

In [27]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9


In [16]:
arr = np.arange(1,11) #1~10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [30]:
arr = np.arange

### 2차원 배열 생성하기

In [31]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
new_arr = arr.reshape(3,4)
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
new_arr = arr.reshape(3,3)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,3)

In [34]:
new_arr = arr.reshape(3,5)
new_arr

ValueError: cannot reshape array of size 12 into shape (3,5)

In [35]:
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수로 생성

In [36]:
arr = np.zeros(4, dtype = int)
arr

array([0, 0, 0, 0])

In [37]:
arr2 = np.zeros((3,4), dtype = int)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 2-4. np.ones() 함수로 생성

In [38]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [39]:
arr2 = np.ones((3,4), dtype = int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2-5. np.linspace() 함수로 생성

In [40]:
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [41]:
arr.dtype = int
arr

array([         0,          0,          0, 1074003968,          0,
       1075052544,          0, 1075707904,          0, 1076101120])

In [42]:
arr = np.linspace(0,10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
arr.shape

(50,)

In [48]:
# (5,10) 인 2차원 배열로 만들기
new_arr = arr.reshape(5,10)
new_arr

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

In [50]:
new_arr.shape

(5, 10)

## 2-6. np.full() 함수로 생성

In [52]:
arr = np.full((4,), 10)
arr

array([10, 10, 10, 10])

In [53]:
arr2 = np.full((3,4), 10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 2-7. np.eye() 함수로 생성

In [55]:
# 단위 행렬, 항등 행렬
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random으로 생성

In [59]:
arr = np.random.randint(5,size = (3,4))
arr

array([[4, 1, 2, 0],
       [4, 1, 2, 2],
       [3, 0, 2, 0]])

In [60]:
np.random.seed(123)
np.random.rand(2,3)

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

## 2-9. Numpy 배열 Save & Load

In [3]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_arr', arr)

In [6]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])