# 3. 연산

## 3-1. 산술연산

In [1]:
import numpy as np

In [4]:
# 1차원 배열
a = np.arange(1,5)
b = np.arange(5,9)

In [5]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [6]:
a+b

array([ 6,  8, 10, 12])

In [7]:
a-b

array([-4, -4, -4, -4])

In [8]:
a*b

array([ 5, 12, 21, 32])

In [9]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [10]:
# 2차원 배열
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

In [11]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [12]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [14]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [15]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [16]:
# 단순곱셈 (이렇게는 안 쓰임)
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

### 행렬의 곱셈 (dot product) ###

In [17]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [20]:
b = np.arange(7,13).reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [18]:
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [21]:
c = np.dot(a,b)
c

array([[ 58,  64],
       [139, 154]])

In [22]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

### 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [23]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [24]:
a+3

array([4, 5, 6])

In [25]:
a-3

array([-2, -1,  0])

In [26]:
a*3

array([3, 6, 9])

In [28]:
a/3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
# max값 찾기
np.max(a)

5

In [4]:
# min값 찾기
np.min(a)

1

In [5]:
a.max(), a.min()

(5, 1)

In [6]:
# sum값 구하기
np.sum(a)

15

In [7]:
# 평균값 구하기
np.mean(a)

3.0

In [8]:
# outlier(이상치)가 존재할때는 평균값이 대표한다고 할 수 있을까? 없다
b = np.array([1,2,3,4,100]) # 이상치 (outlier)
b

array([  1,   2,   3,   4, 100])

In [11]:
# 중앙값(median)
np.median(b)

3.0

In [12]:
# 데이터가 짝수개인 경우
b = np.array([1,3,5,100])
b

array([  1,   3,   5, 100])

In [13]:
np.median(b)

4.0

In [14]:
# 표준편차 (standard deviation)
np.std(a)


1.4142135623730951

### 2차원 배열

In [15]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.max(a), a.max()

(6, 6)

In [19]:
np.min(a), a.min()

(1, 1)

In [22]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a,axis = 0) # 행(row)

array([4, 5, 6])

In [23]:
np.max(a,axis = 1) # 열(column)

array([3, 6])

In [24]:
np.min(a, axis = 0)

array([1, 2, 3])

In [25]:
np.min(a,axis = 1)

array([1, 4])

In [26]:
np.sum(a)

21

In [27]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.sum(a, axis  = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [3]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [5]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [6]:
b = np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.cumsum(b)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [9]:
np.cumsum(b, axis = 0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [10]:
np.cumsum(b,axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [12]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [13]:
# corrcoef (상관계수)
# 키와 몸무게의 상관관계
h = [160,165,170,180]
w = [47,55,78,85]
np.corrcoef(h,w)

array([[1.        , 0.93898324],
       [0.93898324, 1.        ]])

### 비교( (Comparison)

In [31]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [32]:
a >= 3

array([False, False,  True,  True,  True])